# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c88a0af79c910a47b98c958f0685db36da94972063fb01c46f6bdca40aabc59d65d99638a3b2c79b274d0bae260d5291f3e9e76cdc4638398f3cd5a326e6c01

test:
  secret_key_base: de9893fb1b86fff218d47374adde2cbc3533f80beccfd332f92c5bb66216369791d667ba226e34dbd8757c5e08a4dd8bfd7d3e5846d469adda0155dad0cd1a5e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
